### ISSUE TITLE
Layer.js:52 Uncaught TypeError: Cannot read properties of undefined (reading 'addLayer')

### ISSUE THREAD

**Issue by AcapSLP** [HandsOnDataViz/leaflet-maps-with-google-sheets#128]
Map was working fine and then this, both on github and my self hosted one. map just hangs on loading animation.

Failed to load resource: the server responded with a status of 404 ()
Layer.js:52 Uncaught TypeError: Cannot read properties of undefined (reading 'addLayer')
    at i.addTo (Layer.js:52:7)
    at mapPoints (map.js:135:18)
    at onMapDataLoad (map.js:616:15)
    at fetchPolygonsSheet (map.js:1022:21)
    at Object.success (map.js:1032:23)
    at c (jquery.min.js:2:28294)
    at Object.fireWith [as resolveWith] (jquery.min.js:2:29039)
    at l (jquery.min.js:2:79800)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2:82254)

**Comment by JackDougherty** [comment]
Hi AcapSLP 
I checked your GitHub Pages of your public fork of our Leaflet-maps-with-google-sheets (https://acapslp.github.io/didactic-octo-eureka/) and it appears to be working as we designed it. The only 404 error I see is its failure to find the Options.csv file (which is an optional way to load data if you prefer not to use Google Sheets). Perhaps you experienced a momentary error with GitHub Pages service?
![Screen Shot 2022-05-25 at 8 05 53 PM](https://user-images.githubusercontent.com/649719/170389377-e57590dd-ca68-4a40-a84e-f8da3084e535.png)
